# Generated by Django 5.2 on 2025-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seach',
            field=models.BooleanField(default=False),
        ),
    ]
