# Generated by Django 5.2 on 2025-05-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_is_seach'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Client_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
