# Generated by Django 5.2 on 2025-05-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initiator_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferredTheme',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
