# Generated by Django 5.2 on 2025-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_initiator_code_customuser_preferredtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_ITILIUM', models.URLField(default='http://example.com', verbose_name='URL ITILIUM')),
                ('usernameAPI', models.CharField(default='user', max_length=100, verbose_name='Username API')),
                ('passwordAPI', models.CharField(default='password', max_length=100, verbose_name='Passowd API')),
            ],
        ),
    ]
