# Generated by Django 5.2 on 2025-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Text Sate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
            ],
        ),
        migrations.CreateModel(
            name='Usermanual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Text Sate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
            ],
        ),
    ]
