# Generated by Django 5.2 on 2025-06-23 10:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_advertisement_usermanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='title',
            field=models.CharField(max_length=255, verbose_name='header'),
        ),
    ]
