# Generated by Django 5.2 on 2025-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usermanual_content_alter_usermanual_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='URL_ITILIUM',
            field=models.CharField(default='http://example.com', verbose_name='URL ITILIUM'),
        ),
    ]
