# Generated by Django 5.2 on 2025-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_globalsettings_url_itilium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initiator_FIO',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
